try {
    console.log('adad');
    throw new Error()
  
} catch(err) {
    console.log('error caught')
}